---

- hosts: all
  become: true
  gather_facts: false  
  tasks: 

  - name: install apache2 package and php package for apache2
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu","Debian"]


