---

- hosts: all
  become: true
  gather_facts: false
  tasks:



  - name: update respository index
    apt:
      update_cache: yes

  - name: install bridge-utils package
    apt:
      name: bridge-utils
      state: present

  - name: install mosh
    apt:
      name: mosh
      state: present