---

- hosts: all
  become: true
  gather_facts: false  
  tasks: 

  - name: remove apache2 package and remove php support for apache
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: absent
      update_cache: yes

